Only build master and v\d.*
python-desert/desert pull request #49
Opened 2020-01-25 00:08 UTC by altendky

2020-01-25 00:18 UTC, altendky commented
I specifically pushed to `python-desert` rather than `altendky` to test.  It didn't seem to trigger a build and there's only the two (.org and .com) builds for the PR.  A follow-up empty test commit also triggered only those two builds.  It has not been tested against a tag, in case you want to try that out.

I picked a relatively broad regex because I would rather get a build for a v8 branch than miss a build for a release version.

2020-01-25 05:07 UTC, ghost approved these changes

2020-01-25 05:08 UTC, ghost requested changes
Needs a comment

2020-01-25 05:08 UTC, python-desert commented on .travis.yml
> +    - /^v\d.*$/
Needs a comment explaining the conditions under which CI should run.

2020-01-26 01:03 UTC, altendky commented
Kick CI to check #50

2020-01-26 03:00 UTC, ghost approved these changes

2020-01-26 03:05 UTC, merged